### ISSUE TITLE
Build from source failing at UMFPACK

### ISSUE THREAD

**Issue by DeIonizedPlasma** [hansec/OpenFUSIONToolkit#17]
I am trying to build from source on macOS (Sonoma 14.0) with an Apple M2 chip. I was able to follow the macOS build installation steps up to running the following command:

`CC=gcc-13 CXX=g++-13 FC=gfortran-13 python ~/Downloads/OpenFUSIONToolkit-1.0.0-beta1/src/utilities/build_libs.py --nthread=2 --build_umfpack=1 --build_arpack=1 --oblas_threads`

It seemed to properly build OpenBLAS, HDF5, FOX, ARPACK, and METIS, but failed when the process tried to build UMFPACK. There is the following error message in `build/SuiteSparse-7.0.1/build_tmp.log`:

> CMake Error at /opt/homebrew/Cellar/cmake/3.28.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find BLAS (missing: BLAS_LIBRARIES)
Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.28.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /opt/homebrew/Cellar/cmake/3.28.1/share/cmake/Modules/FindBLAS.cmake:1383 (find_package_handle_standard_args) cmake_modules/SuiteSparseBLAS.cmake:69 (find_package)
CMakeLists.txt:65 (include)

In case this has to do with M2 chip issues, I tried adding in the build arguments mentioned in issue #12 by manually editing the relevant arguments in `build_libs.py`, but I still got the same error.

Of possible relevance, I installed `triangle` via conda, because the instructions on the wiki led to some errors when running the python build script. There were no errors installing it via conda, so I'm not sure if triangle install via pip/conda is still considered broken on arm64 chips.

**Comment by hansec** [comment]
Thanks for the report and sorry for the delay. I have not run into this myself, but I haven't upgraded to Sonoma yet either. I'll try and ask around to see if I can reproduce it. Can you check to see if there is anything in the library/include install directories for OpenBLAS?

As for `triangle`, yes [this is a known problem](https://github.com/hansec/OpenFUSIONToolkit/wiki/Building-Triangle-on-arm%E2%80%90based-macs) and you need to do a manual install on arm-based macs.

**Comment by hansec** [comment]
Ok, it looks like this problem is a result of building OpenBLAS with OpenMP. If you remove the `--oblas_threads` from your call to `build_libs` it should work (make sure you remove the old libraries build first). I'll try and sort out how to get UMFPACK to build with a threaded OpenBLAS, but this is not an especially urgent thing as the threaded version of OpenBLAS isn't great anyways. If you are using ThinCurr and want threads, I recommend using Intel oneAPI/MKL on linux.

**Comment by hansec** [comment]
@DeIonizedPlasma, I believe this was fixed in commit 499c2de. Can you try again with the newest version of the code and see if you run into the same issue?

**Comment by DeIonizedPlasma** [comment]
Yep, I was able to run `build_libs.py` and the following make commands without issue.
